@startuml
entity "User" as User {
  * user_id: int <<PK>>
  --
  username: string
  email: string
  password: string
  role: string
  created_at: datetime
}

entity "Game (IGDB)" as Game {
  * game_id: int <<PK>>
  --
  igdb_id: int // Referencia a IGDB
}

entity "Rating" as Rating {
  * rating_id: int <<PK>>
  --
  user_id: int <<FK>>
  game_id: int <<FK>>
  score: int
  review: string
  created_at: datetime
}

entity "Favorite" as Favorite {
  * favorite_id: int <<PK>>
  --
  user_id: int <<FK>>
  game_id: int <<FK>>
  added_at: datetime
}

entity "Recommendation" as Recommendation {
  * recommendation_id: int <<PK>>
  --
  user_id: int <<FK>>
  game_id: int <<FK>>
  reason: string
  created_at: datetime
}

entity "GameStatus" as GameStatus {
  * status_id: int <<PK>>
  --
  user_id: int <<FK>>
  game_id: int <<FK>>
  status: string <<ENUM: "Jugado", "Deseado">>
  updated_at: datetime
}

User ||--|{ Rating : "1 - N"
User ||--|{ Favorite : "1 - N"
User ||--|{ Recommendation : "1 - N"
User ||--|{ GameStatus : "1 - N"

Game ||--|{ Rating : "1 - N"
Game ||--|{ Favorite : "1 - N"
Game ||--|{ Recommendation : "1 - N"
Game ||--|{ GameStatus : "1 - N"
@enduml
