@startuml
entity User {
  +Id_User : UUID [PK]
  +Name : String
  +Email : String
  +Password : String
  +Registration_Date : DateTime
}

entity VideoGame {
  +Id_VideoGame : UUID [PK]
  +Title : String
  +Description : String
  +Release_Date : DateTime?
  +Developer : String
  +Platform : String
  +Rating : Float
  +Id_Category : UUID? [FK]
  +CoverUrl : String
}

entity Category {
  +Id_Category : UUID [PK]
  +Name : String
}

entity Review {
  +Id_Review : UUID [PK]
  +Id_User : UUID [FK]
  +Id_VideoGame : UUID [FK]
  +Comment : String
  +Rating : Float
  +Date : DateTime
}

entity Recommendation {
  +Id_Recommendation : UUID [PK]
  +Id_User : UUID [FK]
  +Id_VideoGame : UUID [FK]
  +Reason : String
  +Date : DateTime
}

entity Purchase {
  +Id_Purchase : UUID [PK]
  +Id_User : UUID [FK]
  +Id_VideoGame : UUID [FK]
  +Store : String
  +Price : Float
  +Link : String
}

entity PlayedGame {
  +Id_Played_Game : UUID [PK]
  +Id_User : UUID [FK]
  +Id_VideoGame : UUID [FK]
  +Played_At : DateTime
}

User "1" -- "0..*" Review
User "1" -- "0..*" Recommendation
User "1" -- "0..*" Purchase
User "1" -- "0..*" PlayedGame
Category "1" -- "0..*" VideoGame
VideoGame "1" -- "0..*" Review
VideoGame "1" -- "0..*" Recommendation
VideoGame "1" -- "0..*" Purchase
VideoGame "1" -- "0..*" PlayedGame
@enduml
