version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: smartgamecatalog_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: SmartGameDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: smartgamecatalog_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@postgres.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - "5050:80"
    depends_on:
      - postgres

  weaviate:
    image: semitechnologies/weaviate:latest
    container_name: smartgamecatalog_weaviate
    restart: always
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      QUERY_DEFAULTS_LIMIT: "10"
      ENABLE_MODULES: "text2vec-huggingface"
      DEFAULT_VECTORIZER_MODULE: "text2vec-huggingface"
      HUGGINGFACE_APIKEY: "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"  # 🔑 Usa esta variable en vez de HUGGINGFACE_INFERENCE_API
      HUGGINGFACE_EMBEDDINGS_MODEL: "sentence-transformers/all-MiniLM-L6-v2"
    ports:
      - "8080:8080"
    volumes:
      - weaviate_data:/var/lib/weaviate



volumes:
  postgres_data:
  weaviate_data:
