name: CI/CD Pipeline - Windows

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependencias
        run: dotnet restore

      - name: Compilar aplicación
        run: dotnet build --no-restore

      - name: Ejecutar pruebas
        run: dotnet test --no-build --verbosity normal

  deploy:
    needs: build
    runs-on: windows-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Publicar aplicación
        run: dotnet publish -c Release -o ./publish

      - name: Transferir archivos al Servidor Windows
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.WINDOWS_SERVER_IP }}
          username: ${{ secrets.WINDOWS_SERVER_USER }}
          password: ${{ secrets.WINDOWS_SERVER_PASSWORD }}
          source: "./publish/*"
          target: "C:/deploy/catalogo-inteligente"

      - name: Reiniciar servicio en Windows Server
        run: |
          net stop "CatalogoInteligenteService"
          net start "CatalogoInteligenteService"
